version: '3.1'

services:

  mongo:
    image: mongo:5.0.3
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ashutosh
      MONGO_INITDB_ROOT_PASSWORD: salikshasha

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ashutosh
      ME_CONFIG_MONGODB_ADMINPASSWORD: salikshash
      ME_CONFIG_MONGODB_URL: mongodb://ashutosh:salikshasha@mongo:27017/